# coding=UTF-8
import xml.etree.ElementTree as ET

def make_xml_template():
	xml_string = '<?xml version="1.0" encoding="utf-8"?><DOC><P ID=""><R Center="" ID="" RelationType="" Sentence="" SentencePosition="" /><R Center="" ID="" RelationType="" Sentence="" SentencePosition="" /> </P></DOC>'
	x_string = '<?xml version="1.0" encoding="utf-8"?><DOC><P ID="2"> <R ID="1" StructureType="逐层切分" ConnectiveType="隐式关系" Layer="1" RelationNumber="单个关系" Connective="" RelationType="并列关系" ConnectivePosition="" ConnectiveAttribute="不可添加" RoleLocation="normal" LanguageSense="true" Sentence="海关统计表明，“八五”期间（一九九０年?一九九五年），中国外商投资企业的进出口呈直线上升之势，出口年均增长百分之四十三点二，进口年均增长百分之三十八点六。|去年实现进出口总值达一千零九十八点二亿美元，占全国进出口总值的比重由上年的百分之三十七提高到百分之三十九。" SentencePosition="1…77|78…130" Center="3" ChildList="2|4" ParentId="-1" UseTime="18"/> <R ID="2" StructureType="逐层切分" ConnectiveType="隐式关系" Layer="2" RelationNumber="单个关系" Connective="" RelationType="解说关系" ConnectivePosition="" ConnectiveAttribute="不可添加" RoleLocation="normal" LanguageSense="true" Sentence="海关统计表明，“八五”期间（一九九０年?一九九五年），中国外商投资企业的进出口呈直线上升之势，|出口年均增长百分之四十三点二，进口年均增长百分之三十八点六。" SentencePosition="1…47|48…77" Center="1" ChildList="3" ParentId="1" UseTime="14"/> <R ID="3" StructureType="逐层切分" ConnectiveType="隐式关系" Layer="3" RelationNumber="单个关系" Connective="" RelationType="并列关系" ConnectivePosition="" ConnectiveAttribute="不可添加" RoleLocation="normal" LanguageSense="true" Sentence="出口年均增长百分之四十三点二，|进口年均增长百分之三十八点六。" SentencePosition="48…62|63…77" Center="3" ChildList="" ParentId="2" UseTime="9"/>    <R ID="4" StructureType="逐层切分" ConnectiveType="隐式关系" Layer="2" RelationNumber="单个关系" Connective="" RelationType="并列关系" ConnectivePosition="" ConnectiveAttribute="不可添加" RoleLocation="normal" LanguageSense="true" Sentence="去年实现进出口总值达一千零九十八点二亿美元，|占全国进出口总值的比重由上年的百分之三十七提高到百分之三十九。" SentencePosition="78…99|100…130" Center="1" ChildList="" ParentId="1" UseTime="11"/></P></DOC>'
	tree = ET.ElementTree(ET.fromstring(xml_string))
	tree.write('template.xml', encoding='utf-8')

make_xml_template()